# Generated by Django 5.1.3 on 2024-11-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0003_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото Продукта', 'verbose_name_plural': 'Фото Продуктов'},
        ),
        migrations.AddField(
            model_name='product',
            name='care_guide',
            field=models.TextField(null=True, verbose_name='Руководство по уходу'),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_info',
            field=models.TextField(null=True, verbose_name='Информация о доставке'),
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.CharField(max_length=250, null=True, verbose_name='Материалы'),
        ),
    ]
