# Generated by Django 5.1.3 on 2024-11-30 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_app', '0004_alter_productimage_options_product_care_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='facility',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='facility',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='care_guide',
            field=models.TextField(blank=True, null=True, verbose_name='Руководство по уходу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о доставке'),
        ),
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.TextField(null=True, verbose_name='Материалы'),
        ),
    ]
